<?php

/**
 * @file
 * service_resume_form_full_package.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function service_resume_form_full_package_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'entityform-service_resume-field__resume_most_fulfilling'.
  $field_instances['entityform-service_resume-field__resume_most_fulfilling'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please list your top two most fulfilling service positions/responsibilities from above',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'field_collection',
        'settings' => array(
          'add' => 'Add',
          'delete' => 'Delete',
          'description' => TRUE,
          'edit' => 'Edit',
          'translate' => 'Translate',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 15,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field__resume_most_fulfilling',
    'label' => 'Most Fulfilling',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 14,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_attend_elaborate'.
  $field_instances['entityform-service_resume-field_attend_elaborate'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 13,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_attend_elaborate',
    'label' => 'Please elaborate',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 2,
      ),
      'type' => 'text_textarea',
      'weight' => 10,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_common_questions'.
  $field_instances['entityform-service_resume-field_common_questions'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'These are questions typically asked during the election process.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'field_collection',
        'settings' => array(
          'add' => 'Add',
          'delete' => 'Delete',
          'description' => TRUE,
          'edit' => 'Edit',
          'translate' => 'Translate',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 16,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_common_questions',
    'label' => 'Common Questions',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'entityform-service_resume-field_resume_address'.
  $field_instances['entityform-service_resume-field_resume_address'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'We use this for location purposes',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'addressfield',
        'settings' => array(
          'format_handlers' => array(
            0 => 'address',
          ),
          'use_widget_handlers' => 1,
        ),
        'type' => 'addressfield_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_address',
    'label' => 'Address',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'addressfield',
      'settings' => array(
        'available_countries' => array(
          'US' => 'US',
        ),
        'default_country' => 'US',
        'format_handlers' => array(
          'address' => 'address',
          'address-hide-country' => 'address-hide-country',
          'address-hide-postal-code' => 0,
          'address-hide-street' => 0,
          'organisation' => 0,
          'name-full' => 0,
          'name-oneline' => 0,
          'address-optional' => 0,
        ),
      ),
      'type' => 'addressfield_standard',
      'weight' => 7,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_attend_na_meetings'.
  $field_instances['entityform-service_resume-field_resume_attend_na_meetings'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_attend_na_meetings',
    'label' => 'Do you attend NA meetings on a regular basis? ',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_clean_date'.
  $field_instances['entityform-service_resume-field_resume_clean_date'] = array(
    'bundle' => 'service_resume',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'long',
          'fromto' => 'both',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
          'show_remaining_days' => FALSE,
        ),
        'type' => 'date_default',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_clean_date',
    'label' => 'Clean Date',
    'required' => 1,
    'settings' => array(
      'default_value' => 'strtotime',
      'default_value2' => 'same',
      'default_value_code' => '-10 years',
      'default_value_code2' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'increment' => 30,
        'input_format' => 'm/d/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'no_fieldset' => 0,
        'text_parts' => array(),
        'year_range' => '-50:+0',
      ),
      'type' => 'date_select',
      'weight' => 7,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_education'.
  $field_instances['entityform-service_resume-field_resume_education'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 17,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_education',
    'label' => 'Education',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_email_address'.
  $field_instances['entityform-service_resume-field_resume_email_address'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'We must have your preferred email address',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'email',
        'settings' => array(),
        'type' => 'email_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_email_address',
    'label' => 'Email Address',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'email',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'email_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_first_name'.
  $field_instances['entityform-service_resume-field_resume_first_name'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'First name or alias',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_first_name',
    'label' => 'First Name',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_last_name'.
  $field_instances['entityform-service_resume-field_resume_last_name'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'This information will not be made public and is not required',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_last_name',
    'label' => 'Last Name',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_life_experience'.
  $field_instances['entityform-service_resume-field_resume_life_experience'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 19,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_life_experience',
    'label' => 'Life Experience',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 10,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_member_area'.
  $field_instances['entityform-service_resume-field_resume_member_area'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'What Area are you a member of?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_member_area',
    'label' => 'Member Area',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_occupation'.
  $field_instances['entityform-service_resume-field_resume_occupation'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 18,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_occupation',
    'label' => 'Occupation',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 9,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_positions_served'.
  $field_instances['entityform-service_resume-field_resume_positions_served'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Choose as many that apply',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'term_reference_tree',
        'settings' => array(
          'token_display_selected' => '',
          'token_display_unselected' => '',
        ),
        'type' => 'term_reference_tree',
        'weight' => 14,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_positions_served',
    'label' => 'Positions Served',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'term_reference_tree',
      'settings' => array(
        'cascading_selection' => 0,
        'filter_view' => '',
        'leaves_only' => 1,
        'max_depth' => '',
        'parent_term_id' => '',
        'select_parents' => 1,
        'start_minimized' => 1,
        'token_display' => '',
        'track_list' => 1,
      ),
      'type' => 'term_reference_tree',
      'weight' => 13,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_regular_basis'.
  $field_instances['entityform-service_resume-field_resume_regular_basis'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_regular_basis',
    'label' => 'What do you consider regular basis?',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 2,
      ),
      'type' => 'text_textarea',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'entityform-service_resume-field_resume_sponsor'.
  $field_instances['entityform-service_resume-field_resume_sponsor'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 10,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_sponsor',
    'label' => 'Do you have an NA Sponsor?',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'entityform-service_resume-field_resume_steps'.
  $field_instances['entityform-service_resume-field_resume_steps'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 12,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_steps',
    'label' => 'Have you worked all Twelve Steps of NA?',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 13,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_resume_telephone'.
  $field_instances['entityform-service_resume-field_resume_telephone'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please give us your phone number',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_resume_telephone',
    'label' => 'Telephone',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'masked_input',
      'settings' => array(
        'mask' => '(999) 999-9999',
        'placeholder' => '_',
        'size' => 14,
      ),
      'type' => 'masked_input',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'entityform-service_resume-field_sponsor_elaborate'.
  $field_instances['entityform-service_resume-field_sponsor_elaborate'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 9,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_sponsor_elaborate',
    'label' => 'Please elaborate',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 2,
      ),
      'type' => 'text_textarea',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'entityform-service_resume-field_steps_elaborate'.
  $field_instances['entityform-service_resume-field_steps_elaborate'] = array(
    'bundle' => 'service_resume',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 11,
      ),
    ),
    'entity_type' => 'entityform',
    'field_name' => 'field_steps_elaborate',
    'label' => 'Please elaborate',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 2,
      ),
      'type' => 'text_textarea',
      'weight' => 14,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field__resume_most_fulfilling-field_rmf_position'.
  $field_instances['field_collection_item-field__resume_most_fulfilling-field_rmf_position'] = array(
    'bundle' => 'field__resume_most_fulfilling',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_rmf_position',
    'label' => 'Position',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field__resume_most_fulfilling-field_rmf_position1'.
  $field_instances['field_collection_item-field__resume_most_fulfilling-field_rmf_position1'] = array(
    'bundle' => 'field__resume_most_fulfilling',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_rmf_position1',
    'label' => 'Position',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field__resume_most_fulfilling-field_rmf_responsibilities'.
  $field_instances['field_collection_item-field__resume_most_fulfilling-field_rmf_responsibilities'] = array(
    'bundle' => 'field__resume_most_fulfilling',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_rmf_responsibilities',
    'label' => 'Responsibilities',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field__resume_most_fulfilling-field_rmf_responsibilities1'.
  $field_instances['field_collection_item-field__resume_most_fulfilling-field_rmf_responsibilities1'] = array(
    'bundle' => 'field__resume_most_fulfilling',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_rmf_responsibilities1',
    'label' => 'Responsibilities',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 5,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field__resume_most_fulfilling-field_rmf_why_fulfilling'.
  $field_instances['field_collection_item-field__resume_most_fulfilling-field_rmf_why_fulfilling'] = array(
    'bundle' => 'field__resume_most_fulfilling',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_rmf_why_fulfilling',
    'label' => 'Why was it fulfilling?',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field__resume_most_fulfilling-field_rmf_why_fulfilling1'.
  $field_instances['field_collection_item-field__resume_most_fulfilling-field_rmf_why_fulfilling1'] = array(
    'bundle' => 'field__resume_most_fulfilling',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_rmf_why_fulfilling1',
    'label' => 'Why was it fulfilling?',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_common_questions-field_have_you_ever_misappropria'.
  $field_instances['field_collection_item-field_common_questions-field_have_you_ever_misappropria'] = array(
    'bundle' => 'field_common_questions',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_have_you_ever_misappropria',
    'label' => 'Have you ever misappropriated NA funds',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_common_questions-field_have_you_ever_not_complete'.
  $field_instances['field_collection_item-field_common_questions-field_have_you_ever_not_complete'] = array(
    'bundle' => 'field_common_questions',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_have_you_ever_not_complete',
    'label' => 'Have you ever not completed a service position?',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_common_questions-field_misapp_elaborate'.
  $field_instances['field_collection_item-field_common_questions-field_misapp_elaborate'] = array(
    'bundle' => 'field_common_questions',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_misapp_elaborate',
    'label' => 'Please elaborate',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_common_questions-field_not_comp_elaborate'.
  $field_instances['field_collection_item-field_common_questions-field_not_comp_elaborate'] = array(
    'bundle' => 'field_common_questions',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_not_comp_elaborate',
    'label' => 'Please elaborate',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Address');
  t('Choose as many that apply');
  t('Clean Date');
  t('Common Questions');
  t('Do you attend NA meetings on a regular basis? ');
  t('Do you have an NA Sponsor?');
  t('Education');
  t('Email Address');
  t('First Name');
  t('First name or alias');
  t('Have you ever misappropriated NA funds');
  t('Have you ever not completed a service position?');
  t('Have you worked all Twelve Steps of NA?');
  t('Last Name');
  t('Life Experience');
  t('Member Area');
  t('Most Fulfilling');
  t('Occupation');
  t('Please elaborate');
  t('Please give us your phone number');
  t('Please list your top two most fulfilling service positions/responsibilities from above');
  t('Position');
  t('Positions Served');
  t('Responsibilities');
  t('Telephone');
  t('These are questions typically asked during the election process.');
  t('This information will not be made public and is not required');
  t('We must have your preferred email address');
  t('We use this for location purposes');
  t('What Area are you a member of?');
  t('What do you consider regular basis?');
  t('Why was it fulfilling?');

  return $field_instances;
}
